kafka_management:
  host: kafka
  port: 9092
  brokers:
    - "kafka:9092"
  partitions: 1
  write_timeout: 500ms
  topic: measurement
kafka_error:
  host: kafka
  port: 9092
  brokers:
    - "kafka:9092"
  partitions: 1
  write_timeout: 500ms
  topic: error
rabbitmq:
  host: "edge-rabbitmq3"
  port: 5672
  username: "guest"
  password: "guest"
  exchange: "measurement"
  queues:
    - "measurement.sensors.sensor1"
    - "measurement.sensors.sensor2"
core:
  record-lifetime: 1500ms
  collect-interval: 1s
  limit:
    - name: sensor1
      upper: 15.0
      lower: -15.0
    - name: sensor2
      upper: 20.0
      lower: -20.0
influxdb:
  host: "edge-influxdb"
  port: 8086
  write-timeout: 500ms
  batch-size: 20
  batch-time: 5s
edge_node_name:
