kafka:
    host: "127.0.0.1"
    port: 9092
    brokers:
        - "127.0.0.1:9092"
    dialer-timeout: 1
    write-timeout: 10
    read-timeout: 10
rabbitmq:
    host: "rabbitmq3"
    port: 5672
    username: "guest"
    password: "guest"
    exchange: "measurement"
    queues:
        - "measurement.sensors.sensor1"
core:
    record-lifetime: 1500ms
    collect-interval: 1s
