kafka:
    host: kafka
    port: 9092
    brokers:
        - "kafka:9092"
    write-timeout: 500ms
    topic: measurement
rabbitmq:
    host: "rabbitmq3"
    port: 5672
    username: "guest"
    password: "guest"
    exchange: "measurement"
    queues:
        - "measurement.sensors.sensor1"
core:
    record-lifetime: 1500ms
    collect-interval: 1s
