version: "3.3"
services:
  fog-processor:
    image: trhoangtuan96/fog-processor:latest
    networks:
      - fog
      - docker_broker
    restart: always
    volumes:
      - ./../fog-node/processor:/app

networks:
  fog:
    driver: bridge
  docker_broker:
    external: true
