version: "3.3"
services:
  influxdb:
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
    image: "influxdb"
    ports:
      - "8086:8086"
      - "2003:2003"
  # telegraf:
  #   hostname: apphost
  #   links:
  #     - influxdb:influxdb
  #   image: "telegraf"
  #   volumes:
  #     - ${PWD}/../configs/telegraf.conf:/etc/telegraf/telegraf.conf:ro
