version: "3.3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - fog

  kafka:
    image: wurstmeister/kafka
    environment:
      # remember to change this host address to the actual network
      KAFKA_ADVERTISED_HOST_NAME: 172.28.0.10
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092:9092"
    networks:
      fog:
        ipv4_address: 172.28.0.10

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: -Xms32M -Xmx64M
      SERVER_SERVLET_CONTEXTPATH: /
    networks:
      - fog

networks:
  fog:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

