version: '3'
services:
  catalog:
    build: .
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: catalog
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: catalog
      DATABASE_PASSWORD: catalog
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
    volumes:
      - ./data:/var/lib/postgresql/data