version: '3'
services:
  catalog:
    build: .
    environment:
      POSTGRES_DEV_HOST: postgres
      POSTGRES_DEV_PORT: 5432
      POSTGRES_DEV_USER: catalog
      POSTGRES_DEV_PASSWORD: catalog
      POSTGRES_DEV_DATABASE: catalog
      PORT: 5000
    volumes:
      - ./app:/srv/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
    volumes:
      - ./data:/var/lib/postgresql/data