kafka:
  host: kafka
  port: 9092
  brokers:
    - "kafka:9092"
  partition: 0
  write_timeout: 500ms
  topic: error
redis:
  address: "fog-redis:6379"
  tll: 20s
  timeout: 100ms
catalog:
  url: "http://fog-catalog:8080/api/v1/contact"
  timeout: 100ms
slackbot:
  token: "xoxb-1607306712658-1607332830498-RYzLHNklwpAGfLmGietTOp9s"
  timeout: 2000ms
  channel: "#errorfognode"