kafka:
  host: kafka
  port: 9092
  brokers:
    - "kafka:9092"
  partition: 0
  write_timeout: 500ms
  topic: measurement
core:
  record-lifetime: 1500ms
  collect-interval: 1s
influxdb:
  host: "fog-influxdb"
  port: 8086
  write-timeout: 500ms
  batch-size: 20
  batch-time: 5s
  